linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes:
      github.com/cloudsigma/cloudsigma-sdk-go
      github.com/cloudsigma/terraform-provider-cloudsigma

output:
  formats:
    - format: tab
  show-stats: true

run:
  timeout: 10m
