dist: xenial
language: go
os: linux
services:
  - docker

go:
  - "1.14.x"

cache:
  directories:
    - .bin/

jobs:
  fast_finish: true
  include:
    - name: "Lint"
      script: make lint
    - name: "Test"
      script: make test
    - name: "Website"
      # enable after our provider is moved to `terraform-providers`
      script: echo "testing website"

install:
  - make tools

branches:
  only:
    - master
