name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Import GPG key
        uses: paultyng/ghaction-import-gpg@v2.1.0
        id: import_gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Generate changelog
        run: |
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
          git-chglog --config .github/changelog/config.yml $(git describe --tags $(git rev-list --tags --max-count=1)) -o DRAFT_CHANGELOG.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release -f .github/goreleaser.yml --rm-dist --release-notes=DRAFT_CHANGELOG.md
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
